name: "Inconsistency in Wiki"
description: "Inconsistency with the C++ programming language."
title: "[Inconsistency]: "
labels: ["inconsistency", "wiki", "bug"]
body:
  - type: markdown
    value: |
      Tack för att du rapporterar en inkonsekvens i wikin! Fyll i informationen nedan så att vi kan undersöka.

  - type: input
    id: wiki-page
    label: Wiki-sida
    description: Vilken sida i wikin är inkonsekvent?
    placeholder: t.ex. https://github.com/barbariand/cpp-glossary/blob/master/docs/SUMMARY.md
    required: true

  - type: textarea
    id: description
    label: Beskriv inkonsekvensen
    description: Förklara tydligt vad som är inkonsekvent och varför.  Referera gärna till relevanta delar av C++-standarden om möjligt.
    placeholder: t.ex. Wikin påstår att X är sant, men enligt C++11-standarden är det faktiskt Y.
    rows: 5
    required: true

  - type: textarea
    id: expected-behavior
    label: Förväntat beteende
    description: Hur borde wikin vara forulerad för att vara korrekt?
    placeholder: t.ex. Sidan borde säga X istället för Y.
    rows: 5
    required: true

  - type: textarea
    id: supporting-evidence
    label: Bevis (Valfritt)
    description:  Länkar till C++-refernsen, andra källor, eller kodexempel som stöder ditt påstående.
    placeholder: t.ex. [Länk till C++-refernsen](https://en.cppreference.com/w/)
    rows: 5

  - type: textarea
    id: additional-context
    label: Ytterligare sammanhang (Valfritt)
    description: Lägg till annan information som kan vara användbar.
    rows: 5
