name: "Code Feature Request"
description: "Propose a new feature or improvement in the code."
title: "[Feature]: "
labels: ["enhancement", "code"]
body:
  - type: markdown
    attributes:
      value: |
      Tack för att du föreslår en ny funktion eller förbättring i koden! Fyll i informationen nedan så att vi kan utvärdera ditt förslag.

  - type: textarea
    id: description
    attributes:
      label: Beskriv funktionen/förbättringen
      description: Förklara tydligt vilken ny funktion du vill ha eller vilken förbättring du föreslår.
      placeholder: Beskriv funktionen/förbättringen här.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivering
      description: Förklara varför du anser att den här funktionen/förbättringen är viktig. Vilka problem löser den eller vilka fördelar ger den?
      placeholder: Motivera ditt förslag här.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Föreslagen lösning (Valfritt)
      description: Beskriv hur du skulle implementera den här funktionen/förbättringen.  Detta är valfritt, men hjälper oss att förstå ditt förslag bättre.
      placeholder: Beskriv din föreslagna lösning här.

  - type: textarea
    id: example-usage
    attributes:
      label: Exempelanvändning (Valfritt)
      description: Ge ett exempel på hur den nya funktionen/förbättringen skulle användas i praktiken.
      placeholder: Ge ett exempel här.

  - type: input
    id: relevant-code
    attributes:
      label: Relevant kod (om tillämpligt)
      description: Om din funktion/förbättring relaterar till specifik kod i `barbariand/cpp-glossary`, ange filnamn och/eller relevanta rader.
      placeholder: t.ex. exempel/min_funktion.cpp, rad 10-20


  - type: textarea
    id: additional-context
    attributes:
      label: Ytterligare sammanhang (Valfritt)
      description: Lägg till annan information som kan vara användbar.
