blank_issues_enabled: false
issue_templates:
  - name: "Build Failure"
    description: "Report an example failing to compile"
    title: "[Build]: "
    labels: ["building", "bug"]
    body: "./ISSUE_TEMPLATE/compilation_failure.md"
  - name: "Execution Failure"
    description: "Report an example not running as expected"
    title: "[Execution]: "
    labels: ["execution", "bug"]
    body: "./ISSUE_TEMPLATE/code/execution_failure.md"
  - name: "Code Feature Request"
    description: "Propose a new feature or improvement in the code."
    title: "[Feature]: "
    labels: ["enhancement", "code"]
    body: "./ISSUE_TEMPLATE/code/feature_request.md"
  - name: "Wiki Feature Request"
    description: "Suggest updates or additions to the Wiki."
    title: "[Docs]: "
    labels: ["enhancement", "wiki"]
    body: "./ISSUE_TEMPLATE/wiki/feature_request.md"
  - name: "Incosistency in Wiki"
    description: "Incosistency with the C++ programing language."
    title: "[Incosistency]: "
    labels: ["incosistency", "wiki", "bug"]
    body: "./ISSUE_TEMPLATE/incosistency.md"
  - name: "General Report"
    description: "Provide general feedback or inquiries."
    title: "[General]: "
    labels: ["general"]
    body: "./ISSUE_TEMPLATE/general_report.md"
