name: General Report
title: "[General]: "
labels: general
body:
  - type: markdown
    attributes:
      value: "Tack för din allmänna feedback eller fråga! Fyll i informationen nedan."

  - type: textarea
    id: feedback
    attributes:
      label: Feedback / Fråga
      description: Beskriv din feedback eller ställ din fråga här.
      placeholder: Skriv din feedback eller fråga här.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Ytterligare sammanhang (Valfritt)
      description: Lägg till annan information som kan vara relevant.
